language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - npm ci

script:
  - pm2 reload ecosystem.config.js --env production && pm2 save

deploy:
  provider: templateShop-BE
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: develop
